sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.65.100
    port: 3306
    database: sky_take_out
    username: root
    password: abc123
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t6Fuxb5SVj1stE8Qtux
    access-key-secret: tvL8lkB27dg5csXdKa6yEHPRVahkVE
    bucket-name: sky-take-out-952710086
  redis:
    host: 192.168.65.100
    port: 6379
    password: 123456
    database: 10